# Generated by Django 2.2.1 on 2021-12-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0020_auto_20190818_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('id_no', models.IntegerField()),
                ('age', models.IntegerField()),
                ('contact_no', models.CharField(blank=True, max_length=14, null=True)),
                ('blood_gp', models.CharField(blank=True, max_length=150, null=True)),
                ('email_id', models.CharField(max_length=100)),
                ('test_result', models.CharField(max_length=15)),
            ],
        ),
    ]
